/*
 * Tencent is pleased to support the open source community by making TKEStack
 * available.
 *
 * Copyright (C) 2012-2019 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package internalversion

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	auth "tkestack.io/tke/api/auth"
	scheme "tkestack.io/tke/api/client/clientset/internalversion/scheme"
)

// ProjectPoliciesGetter has a method to return a ProjectPolicyInterface.
// A group's client should implement this interface.
type ProjectPoliciesGetter interface {
	ProjectPolicies() ProjectPolicyInterface
}

// ProjectPolicyInterface has methods to work with ProjectPolicy resources.
type ProjectPolicyInterface interface {
	Create(*auth.ProjectPolicy) (*auth.ProjectPolicy, error)
	Update(*auth.ProjectPolicy) (*auth.ProjectPolicy, error)
	UpdateStatus(*auth.ProjectPolicy) (*auth.ProjectPolicy, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*auth.ProjectPolicy, error)
	List(opts v1.ListOptions) (*auth.ProjectPolicyList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *auth.ProjectPolicy, err error)
	ProjectPolicyExpansion
}

// projectPolicies implements ProjectPolicyInterface
type projectPolicies struct {
	client rest.Interface
}

// newProjectPolicies returns a ProjectPolicies
func newProjectPolicies(c *AuthClient) *projectPolicies {
	return &projectPolicies{
		client: c.RESTClient(),
	}
}

// Get takes name of the projectPolicy, and returns the corresponding projectPolicy object, and an error if there is any.
func (c *projectPolicies) Get(name string, options v1.GetOptions) (result *auth.ProjectPolicy, err error) {
	result = &auth.ProjectPolicy{}
	err = c.client.Get().
		Resource("projectpolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ProjectPolicies that match those selectors.
func (c *projectPolicies) List(opts v1.ListOptions) (result *auth.ProjectPolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &auth.ProjectPolicyList{}
	err = c.client.Get().
		Resource("projectpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested projectPolicies.
func (c *projectPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("projectpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a projectPolicy and creates it.  Returns the server's representation of the projectPolicy, and an error, if there is any.
func (c *projectPolicies) Create(projectPolicy *auth.ProjectPolicy) (result *auth.ProjectPolicy, err error) {
	result = &auth.ProjectPolicy{}
	err = c.client.Post().
		Resource("projectpolicies").
		Body(projectPolicy).
		Do().
		Into(result)
	return
}

// Update takes the representation of a projectPolicy and updates it. Returns the server's representation of the projectPolicy, and an error, if there is any.
func (c *projectPolicies) Update(projectPolicy *auth.ProjectPolicy) (result *auth.ProjectPolicy, err error) {
	result = &auth.ProjectPolicy{}
	err = c.client.Put().
		Resource("projectpolicies").
		Name(projectPolicy.Name).
		Body(projectPolicy).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *projectPolicies) UpdateStatus(projectPolicy *auth.ProjectPolicy) (result *auth.ProjectPolicy, err error) {
	result = &auth.ProjectPolicy{}
	err = c.client.Put().
		Resource("projectpolicies").
		Name(projectPolicy.Name).
		SubResource("status").
		Body(projectPolicy).
		Do().
		Into(result)
	return
}

// Delete takes name of the projectPolicy and deletes it. Returns an error if one occurs.
func (c *projectPolicies) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("projectpolicies").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *projectPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("projectpolicies").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched projectPolicy.
func (c *projectPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *auth.ProjectPolicy, err error) {
	result = &auth.ProjectPolicy{}
	err = c.client.Patch(pt).
		Resource("projectpolicies").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
