/*
 * Tencent is pleased to support the open source community by making TKEStack
 * available.
 *
 * Copyright (C) 2012-2019 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	authv1 "tkestack.io/tke/api/auth/v1"
)

// FakeProjectPolicies implements ProjectPolicyInterface
type FakeProjectPolicies struct {
	Fake *FakeAuthV1
}

var projectpoliciesResource = schema.GroupVersionResource{Group: "auth.tkestack.io", Version: "v1", Resource: "projectpolicies"}

var projectpoliciesKind = schema.GroupVersionKind{Group: "auth.tkestack.io", Version: "v1", Kind: "ProjectPolicy"}

// Get takes name of the projectPolicy, and returns the corresponding projectPolicy object, and an error if there is any.
func (c *FakeProjectPolicies) Get(name string, options v1.GetOptions) (result *authv1.ProjectPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(projectpoliciesResource, name), &authv1.ProjectPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*authv1.ProjectPolicy), err
}

// List takes label and field selectors, and returns the list of ProjectPolicies that match those selectors.
func (c *FakeProjectPolicies) List(opts v1.ListOptions) (result *authv1.ProjectPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(projectpoliciesResource, projectpoliciesKind, opts), &authv1.ProjectPolicyList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &authv1.ProjectPolicyList{ListMeta: obj.(*authv1.ProjectPolicyList).ListMeta}
	for _, item := range obj.(*authv1.ProjectPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested projectPolicies.
func (c *FakeProjectPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(projectpoliciesResource, opts))
}

// Create takes the representation of a projectPolicy and creates it.  Returns the server's representation of the projectPolicy, and an error, if there is any.
func (c *FakeProjectPolicies) Create(projectPolicy *authv1.ProjectPolicy) (result *authv1.ProjectPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(projectpoliciesResource, projectPolicy), &authv1.ProjectPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*authv1.ProjectPolicy), err
}

// Update takes the representation of a projectPolicy and updates it. Returns the server's representation of the projectPolicy, and an error, if there is any.
func (c *FakeProjectPolicies) Update(projectPolicy *authv1.ProjectPolicy) (result *authv1.ProjectPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(projectpoliciesResource, projectPolicy), &authv1.ProjectPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*authv1.ProjectPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProjectPolicies) UpdateStatus(projectPolicy *authv1.ProjectPolicy) (*authv1.ProjectPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(projectpoliciesResource, "status", projectPolicy), &authv1.ProjectPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*authv1.ProjectPolicy), err
}

// Delete takes name of the projectPolicy and deletes it. Returns an error if one occurs.
func (c *FakeProjectPolicies) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(projectpoliciesResource, name), &authv1.ProjectPolicy{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProjectPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(projectpoliciesResource, listOptions)

	_, err := c.Fake.Invokes(action, &authv1.ProjectPolicyList{})
	return err
}

// Patch applies the patch and returns the patched projectPolicy.
func (c *FakeProjectPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *authv1.ProjectPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(projectpoliciesResource, name, pt, data, subresources...), &authv1.ProjectPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*authv1.ProjectPolicy), err
}
